### PR TITLE
Add Scotland tour page

### PR DESCRIPTION
**Pull request by HelenaWe**

### CODE REVIEW

**Review by gandreadis — COMMENTED** [review]
Awesome, looking very good already! Two minor things:

- Could you compress the tour logo picture? With almost 3 MB it takes quite long to load this, and the level of detail it has is not required I think.
- I know this was also incorrect on the previous tour page, but could you have a look at the positioning of the top banner (the red one)? I think a part of the banner is hiding under the navigation bar, some top margin should be able to fix this. Let me know if you need help, I can also have a look if needed.

**Comment by HelenaWe** [comment]
> Awesome, looking very good already! Two minor things:
> 
> * Could you compress the tour logo picture? With almost 3 MB it takes quite long to load this, and the level of detail it has is not required I think.
> * I know this was also incorrect on the previous tour page, but could you have a look at the positioning of the top banner (the red one)? I think a part of the banner is hiding under the navigation bar, some top margin should be able to fix this. Let me know if you need help, I can also have a look if needed.

Yes good points! I changed the image size and the header should be fixed.

**Review by gandreadis — APPROVED** [review]
Great, thanks!

**Comment by gandreadis** [comment]
I'll create an issue to at some point also create a banner on the homepage to point to this tour page, since it's a bit hidden from the normal Krashna page viewer (no links in navbar or anything of the like).

**Pull request merged**
